name: WobbleBounty
version: 1.0.0
main: me.wobble.wobblebounty.WobbleBounty
api-version: '1.21'
authors: [Wobble]
website: https://github.com/mororpm
depend: [Vault]

commands:
  bounty:
    description: Main bounty command
    usage: /bounty
    aliases: [wbounty]

permissions:
  wobble.bounty.admin:
    description: Full admin access to WobbleBounty
    default: op

  wobble.bounty.reload:
    description: Reload WobbleBounty configuration
    default: op
