name: WBountyHunters
version: 1.0.0
main: me.wobble.wbountyhunters.WBountyHunters
api-version: '1.21'
authors: [Wobble]
website: https://github.com/wobblexdd
depend: [Vault]

commands:
  bounty:
    description: Main bounty command
    usage: /bounty
    aliases: [wbounty]

permissions:
  wobble.bounty.admin:
    description: Full admin access to WBountyHunters
    default: op

  wobble.bounty.reload:
    description: Reload WBountyHunters configuration
    default: op

  wobble.bounty.bypass:
    description: Reserved bypass permission
    default: false
