name: KBountyHunters
version: 1.0.0
main: me.klouse.kbountyhunters.KBountyHunters
api-version: '1.21'
authors: [Klouse]
website: https://github.com/klousex
depend: [Vault]

commands:
  bounty:
    description: Main bounty command
    usage: /bounty
    aliases: [kbounty]

permissions:
  klouse.bounty.admin:
    description: Full admin access to KBountyHunters
    default: op

  klouse.bounty.reload:
    description: Reload KBountyHunters configuration
    default: op

  klouse.bounty.bypass:
    description: Reserved bypass permission
    default: false
